name: flutter_sidekick
description: Widgets for creating Hero-like animations between two widgets within the same screen
version: 0.1.3
author: Romain Rastel <lets4r@gmail.com> modified by Mohamed Sadakathulla <sadakkathullah@gmail.com>
homepage: https://github.com/sad1996/flutter_sidekick

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
